# Generated by Django 5.2.8 on 2026-05-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_room_students_data_is_active_students_data_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_data',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='students_data',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
