# Generated by Django 6.0.6 on 2026-07-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_room_students_data_is_active_students_data_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_data',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
